-- Attach masks to PII columns on base tables.
ALTER TABLE investsphere.silver_cdc.customer_scd2 ALTER COLUMN customer_name SET MASK investsphere.governance.mask_name;
ALTER TABLE investsphere.silver_cdc.customer_scd2 ALTER COLUMN email SET MASK investsphere.governance.mask_email;
ALTER TABLE investsphere.silver_cdc.customer_scd2 ALTER COLUMN phone_number SET MASK investsphere.governance.mask_phone;
ALTER TABLE investsphere.silver_cdc.customer_scd2 ALTER COLUMN national_id SET MASK investsphere.governance.mask_id;
ALTER TABLE investsphere.silver_cdc.customer_scd2 ALTER COLUMN passport_number SET MASK investsphere.governance.mask_id;
ALTER TABLE investsphere.silver_cdc.customer_scd2 ALTER COLUMN emirates_id SET MASK investsphere.governance.mask_id;
ALTER TABLE investsphere.gold.dim_customer ALTER COLUMN customer_name SET MASK investsphere.governance.mask_name;
ALTER TABLE investsphere.gold.dim_customer ALTER COLUMN email SET MASK investsphere.governance.mask_email;
ALTER TABLE investsphere.gold.dim_customer ALTER COLUMN phone_number SET MASK investsphere.governance.mask_phone;
ALTER TABLE investsphere.gold.dim_customer ALTER COLUMN national_id SET MASK investsphere.governance.mask_id;
ALTER TABLE investsphere.gold.dim_customer ALTER COLUMN passport_number SET MASK investsphere.governance.mask_id;
ALTER TABLE investsphere.gold.dim_customer ALTER COLUMN emirates_id SET MASK investsphere.governance.mask_id;
ALTER TABLE investsphere.gold.dim_customer_history ALTER COLUMN customer_name SET MASK investsphere.governance.mask_name;
ALTER TABLE investsphere.gold.dim_customer_history ALTER COLUMN email SET MASK investsphere.governance.mask_email;
ALTER TABLE investsphere.gold.dim_customer_history ALTER COLUMN phone_number SET MASK investsphere.governance.mask_phone;
ALTER TABLE investsphere.gold.dim_customer_history ALTER COLUMN national_id SET MASK investsphere.governance.mask_id;
ALTER TABLE investsphere.gold.dim_customer_history ALTER COLUMN passport_number SET MASK investsphere.governance.mask_id;
ALTER TABLE investsphere.gold.dim_customer_history ALTER COLUMN emirates_id SET MASK investsphere.governance.mask_id;
