-- Groups are account-level (SCIM/Terraform); referenced here:
--   data_engineers, analysts, pii_approved_users, data_stewards, spn_investsphere_etl

GRANT USE CATALOG ON CATALOG investsphere TO `data_engineers`;
GRANT USE CATALOG ON CATALOG investsphere TO `analysts`;
GRANT USE CATALOG ON CATALOG investsphere TO `pii_approved_users`;
GRANT USE CATALOG ON CATALOG investsphere TO `data_stewards`;
GRANT USE CATALOG ON CATALOG investsphere TO `spn_investsphere_etl`;
GRANT USE SCHEMA ON SCHEMA investsphere.gold TO `spn_investsphere_etl`;
GRANT USE SCHEMA ON SCHEMA investsphere.gold_marts TO `spn_investsphere_etl`;
GRANT USE SCHEMA ON SCHEMA investsphere.silver_cdc TO `spn_investsphere_etl`;
GRANT USE SCHEMA ON SCHEMA investsphere.silver_clean TO `spn_investsphere_etl`;
GRANT USE SCHEMA ON SCHEMA investsphere.silver_control TO `spn_investsphere_etl`;
GRANT USE SCHEMA ON SCHEMA investsphere.silver_quarantine TO `spn_investsphere_etl`;
GRANT SELECT ON TABLE investsphere.silver_clean.payment_clean TO `spn_investsphere_etl`;
GRANT MODIFY ON TABLE investsphere.silver_clean.payment_clean TO `spn_investsphere_etl`;
GRANT SELECT ON TABLE investsphere.silver_cdc.customer_scd2 TO `spn_investsphere_etl`;
GRANT MODIFY ON TABLE investsphere.silver_cdc.customer_scd2 TO `spn_investsphere_etl`;
GRANT SELECT ON TABLE investsphere.silver_quarantine.failed_records TO `spn_investsphere_etl`;
GRANT MODIFY ON TABLE investsphere.silver_quarantine.failed_records TO `spn_investsphere_etl`;
GRANT SELECT ON TABLE investsphere.silver_control.table_load_status TO `spn_investsphere_etl`;
GRANT MODIFY ON TABLE investsphere.silver_control.table_load_status TO `spn_investsphere_etl`;
GRANT SELECT ON TABLE investsphere.silver_control.pipeline_run TO `spn_investsphere_etl`;
GRANT MODIFY ON TABLE investsphere.silver_control.pipeline_run TO `spn_investsphere_etl`;
GRANT SELECT ON TABLE investsphere.gold.dim_customer TO `spn_investsphere_etl`;
GRANT MODIFY ON TABLE investsphere.gold.dim_customer TO `spn_investsphere_etl`;
GRANT SELECT ON TABLE investsphere.gold.dim_customer_history TO `spn_investsphere_etl`;
GRANT MODIFY ON TABLE investsphere.gold.dim_customer_history TO `spn_investsphere_etl`;
GRANT SELECT ON TABLE investsphere.gold.fact_payments TO `spn_investsphere_etl`;
GRANT MODIFY ON TABLE investsphere.gold.fact_payments TO `spn_investsphere_etl`;
GRANT SELECT ON TABLE investsphere.gold_marts.daily_payment_summary TO `spn_investsphere_etl`;
GRANT MODIFY ON TABLE investsphere.gold_marts.daily_payment_summary TO `spn_investsphere_etl`;
GRANT USE SCHEMA ON SCHEMA investsphere.silver_control TO `data_engineers`;
GRANT USE SCHEMA ON SCHEMA investsphere.gold TO `data_engineers`;
GRANT USE SCHEMA ON SCHEMA investsphere.gold_marts TO `data_engineers`;
GRANT USE SCHEMA ON SCHEMA investsphere.gold_masked TO `data_engineers`;
GRANT SELECT ON TABLE investsphere.silver_control.table_load_status TO `data_engineers`;
GRANT SELECT ON TABLE investsphere.silver_control.pipeline_run TO `data_engineers`;
GRANT SELECT ON TABLE investsphere.gold.fact_payments TO `data_engineers`;
GRANT SELECT ON TABLE investsphere.gold_marts.daily_payment_summary TO `data_engineers`;
GRANT SELECT ON VIEW investsphere.gold_masked.v_customer_engineer TO `data_engineers`;
GRANT USE SCHEMA ON SCHEMA investsphere.gold_marts TO `analysts`;
GRANT USE SCHEMA ON SCHEMA investsphere.gold_masked TO `analysts`;
GRANT SELECT ON TABLE investsphere.gold_marts.daily_payment_summary TO `analysts`;
GRANT SELECT ON VIEW investsphere.gold_masked.v_customer_masked_for_analytics TO `analysts`;
GRANT USE SCHEMA ON SCHEMA investsphere.gold TO `pii_approved_users`;
GRANT USE SCHEMA ON SCHEMA investsphere.silver_cdc TO `pii_approved_users`;
GRANT SELECT ON TABLE investsphere.silver_cdc.customer_scd2 TO `pii_approved_users`;
GRANT SELECT ON TABLE investsphere.gold.dim_customer TO `pii_approved_users`;
GRANT SELECT ON TABLE investsphere.gold.dim_customer_history TO `pii_approved_users`;
GRANT USE SCHEMA ON SCHEMA investsphere.silver_quarantine TO `data_stewards`;
GRANT USE SCHEMA ON SCHEMA investsphere.silver_control TO `data_stewards`;
GRANT SELECT ON TABLE investsphere.silver_quarantine.failed_records TO `data_stewards`;
GRANT SELECT ON TABLE investsphere.silver_control.table_load_status TO `data_stewards`;
GRANT SELECT ON TABLE investsphere.silver_control.pipeline_run TO `data_stewards`;
